# Generated by Django 4.0.2 on 2022-12-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=22, verbose_name='用户名')),
                ('password', models.CharField(max_length=22, verbose_name='密码')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='昵称')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('is_stats', models.CharField(max_length=2, verbose_name='启用状态')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
