# Generated by Django 4.0.2 on 2022-12-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wikipedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='中草药名称')),
                ('describe', models.CharField(max_length=200, null=True, verbose_name='描述')),
                ('efficacy', models.TextField(null=True, verbose_name='功效作用')),
                ('environment', models.TextField(null=True, verbose_name='生长环境')),
                ('cultivation', models.TextField(null=True, verbose_name='栽培技术')),
                ('oviews', models.IntegerField(default=0, verbose_name='评论量')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '百科表',
                'verbose_name_plural': '百科表',
                'db_table': 'wikipedia',
            },
        ),
    ]
